
import os
import asyncio
from pyrogram import Client, filters
from pyrogram.enums import ParseMode
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery
from bot import Bot
from helper_func import subscribed, encode, decode, get_messages
from pyrogram import __version__
from config import OWNER_ID, BOT_USERNM


@Bot.on_callback_query(group=377)
async def bot_nots(client: Bot, query: CallbackQuery):
    data = query.data
    chemualn_info = [] 
    if data == "aln_chem":
      chemualn_info = [
        f'''  🔮 **CHEMISTRY 11 th  ALLEN CLASSROOM LECTURES**
        
        
🌱**[CHEMICAL EQUILIBRIUM ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU3OTgxNzYwODIzMTUyMDgtNTgwNTE4OTYwMDk5MDg5Ng)**

🌱**[THERMODYNAMICS ✘ TNM SIR  ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyNjIyMTU0OTIzMzk1MzYtNDI3NjI0MjUyOTY5MDkxMg)**

🌱**[BOG ✘ TNM SIR  ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyNzYyNDI1Mjk2OTA5MTItNDI3ODI0NjM5MjE2OTY4MA)**

🌱**[ATOMIC STRUTURE  ✘ TNM SIR  ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyNzkyNDgzMjM0MDkwNjQtNDI4NzI2Mzc3MzMyNDEzNg)**

🌱**[MOLE CONCEPT  ✘ TNM SIR  ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyODgyNjU3MDQ1NjM1MjAtNDI5MjI3MzQyOTUyMTA1Ng)**

🌱**[MOLE CONCEPT RKJ SIR 2025 ](https://t.me/{BOT_USERNM}?start=Z2V0LTEzODc0NzQzODAyOTg5NjMyLTEzODg2NzY2OTc3ODYyMjQw)**

🌱**[REDOX DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDc0OTAwNjE1MzgwNjQ4LTE0NDc5OTEwMjcxNTc3NTY4)** 

🌱**[CHEMICAL EQUILLIBRIUM DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDc5OTEwMjcxNTc3NTY4LTE0NDkwOTMxNTE1MjEwNzky)** 

🌱**[CHEMICAL EQUILLIBRIUM VJ SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzEyMzU4MzE5MTE0NjU2LTE0NzE5MzcxODM3NzkwMzQ0)**

**🌱[CHEMICAL EQUILLIBRIUM VK SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0OTUzODIzNzQ3ODA2MjAwLTE0OTYyODQxMTI4OTYwNjU2)**

🌱**[IONIC EQUILLIBRIUM DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDkxOTMzNDQ2NDUwMTc2LTE0NTE1OTc5Nzk2MTk1Mzky)** 

**🌱[IONIC EQUILLIBRIUM VK SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0OTYyODQxMTI4OTYwNjU2LTE0OTc0ODY0MzAzODMzMjY0)**

🌱**[PERIODIC TABLE ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQxNTkwMTY1NzQ2ODI5ODQtNDE2OTAzNTg4NzA3NjgyNA)**

🌱**[PERIODIC TABLE RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDE1MDE0MTc2NTAzMzkyLTE0MDI0MDMxNTU3NjU3ODQ4)**

🌱**[PERIODIC TABLE MM SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MTUyMjc4NzU2Mjk5MDAwLTE0MTY2MzA1NzkzNjUwMzc2)**

🌱 **[PERIODIC TABLE SKM SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NTE2OTgxNzI3NDM0Nzc2LTE0NTQwMDI2MTQ1OTQwNjA4)**

🌱**[PERIODIC TABLE AS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzI2Mzg1MzU2NDY2MDMyLTE0NzM5NDEwNDYyNTc4MDI0)**

🌱**[PERIODIC TABLE AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzUxNDMzNjM3NDUwNjMyLTE0NzY0NDU4NzQzNTYyNjI0)**

**🌱[PERIODIC TABLE RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MjU3NDA4OTEzMzM5NTUyLTE1MjY4NDMwMTU2OTcyNzc2)**

🌱**[CHEMICAL BONDING ✘ MM SIR](https://t.me/{BOT_USERNM}?start=Z2V0LTQxNjkwMzU4ODcwNzY4MjQtNDE4NjA2ODcxODE0NjM1Mg)**

🌱**[CHEMICAL BONDING RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDI1MDMzNDg4ODk3MjMyLTE0MDQ0MDcwMTgyNDQ1NTI4)**

🌱**[CHEMICAL BONDING SKM SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NTQwMDI2MTQ1OTQwNjA4LTE0NTYyMDY4NjMzMjA3MDU2)**

🌱**[CHEMICAL BONDING AS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzQwNDEyMzkzODE3NDA4LTE0NzUwNDMxNzA2MjExMjQ4)**

🌱**[CHEMICAL BONDING AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzY1NDYwNjc0ODAyMDA4LTE0Nzc1NDc5OTg3MTk1ODQ4)**

**🌱[CHEMICAL BONDING RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MjY5NDMyMDg4MjEyMTYwLTE1Mjg5NDcwNzEyOTk5ODQw)**

🌱**[S BLOCK ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQxODcwNzA2NDkzODU3MzYtNDE4OTA3NDUxMTg2NDUwNA)**

🌱**[COORDINATION COMPOUND ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQxODkwNzQ1MTE4NjQ1MDQtNDE5OTA5MzgyNDI1ODM0NA)**

🌱**[COORDINATION COMPOUND RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDQ1MDcyMTEzNjg0OTEyLTE0MDU0MDg5NDk0ODM5MzY4)**

🌱**[COORDINATION COMPOUND AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0Nzc2NDgxOTE4NDM1MjMyLTE0NzkwNTA4OTU1Nzg2NjA4)**

**🌱[COORDINATION COMPOUND RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MjkwNDcyNjQ0MjM5MjI0LTE1MzAxNDkzODg3ODcyNDQ4)**

🌱**[D AND F BLOCK  ✘ MM SIR](https://t.me/{BOT_USERNM}?start=Z2V0LTQxOTkwOTM4MjQyNTgzNDQtNDIwMDA5NTc1NTQ5NzcyOA)**

🌱**[D & F BLOCK RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDU1MDkxNDI2MDc4NzUyLTE0MDU5MDk5MTUxMDM2Mjg4)**

🌱**[D & F BLOCK SKM SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NTc3MDk3NjAxNzk3ODE2LTE0NTgwMTAzMzk1NTE1OTY4)**

🌱**[D BLOCK AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0Nzk2NTIwNTQzMjIyOTEyLTE0ODAxNTMwMTk5NDE5ODMy)**

**🌱[D BLOCK RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MzAyNDk1ODE5MTExODMyLTE1MzA1NTAxNjEyODI5OTg0)**

🌱**[METALLURGY ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyMDEwOTc2ODY3MzcxMTItNDIwMjA5OTYxNzk3NjQ5Ng)**

🌱**[HYDROGEN AND ITS COMPOUND ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyMDMxMDE1NDkyMTU4ODAtNDIwMzEwMTU0OTIxNTg4MA)**

🌱**[P BLOCK ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyMDQxMDM0ODA0NTUyNjQtNDIxNDEyMjc5Mjg0OTEwNA)**

🌱**[P BLOCK RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDYwMTAxMDgyMjc1NjcyLTE0MDcxMTIyMzI1OTA4ODk2)**

🌱**[P BLOCK SKM SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NTYzMDcwNTY0NDQ2NDQwLTE0NTc2MDk1NjcwNTU4NDMy)**

🌱**[P BLOCK AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzkxNTEwODg3MDI1OTkyLTE0Nzk1NTE4NjExOTgzNTI4)**

**🌱[P BLOCK RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MzA2NTAzNTQ0MDY5MzY4LTE1MzE0NTE4OTkzOTg0NDQw)**

**🌱[PRACTICAL CHEMISTRY RAM RAI SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MzE1NTIwOTI1MjIzODI0LTE1MzE3NTI0Nzg3NzAyNTky)**

🌱 **[SALT ANALYSIS RS SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MDcyMTI0MjU3MTQ4MjgwLTE0MDc3MTMzOTEzMzQ1MjAw)**

🌱**[SALT ANALYSIS AG SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0ODAyNTMyMTMwNjU5MjE2LTE0ODA1NTM3OTI0Mzc3MzY4)**

🌱 **[HYDROCARBON AB SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MjA1MzgxMTExOTg2MzUyLTE0MjExMzkyNjk5NDIyNjU2)**

🌱 **[NOMENCLATURE AB SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MTY3MzA3NzI0ODg5NzYwLTE0MTc0MzIxMjQzNTY1NDQ4)**

🌱 **[NOMENCLATURE DN SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MzM3NjM2MDM1NTg1MDQwLTE0MzQ4NjU3Mjc5MjE4MjY0)**
''',
          f'''

🌱 **[ISOMERISM AB SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MTc1MzIzMTc0ODA0ODMyLTE0MTg5MzUwMjEyMTU2MjA4)**

🌱 **[ISOMERISM DN SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MzQ5NjU5MjEwNDU3NjQ4LTE0MzYzNjg2MjQ3ODA5MDI0)**

🌱 **[GOC AB SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MTkwMzUyMTQzMzk1NTkyLTE0MjA0Mzc5MTgwNzQ2OTY4)**

🌱 **[GOC 1 DN SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MzY0Njg4MTc5MDQ4NDA4LTE0MzgyNzIyOTQxMzU3MzIw)**

🌱 **[GOC 2 DN SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0MzgyNzIyOTQxMzU3MzIwLTE0NDIwNzk2MzI4NDUzOTEy)**

🌱**[ORGANIC LEC 01- 45 ✘  AKASH BAGRA SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU2NTg5MDc2NDAwNDA4MzItNTcwMjk5MjYxNDU3MzcyOA)**

🌱**[ORGANIC LEC 46-75 ✘ AKASH BAGRA SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU3MDM5OTQ1NDU4MTMxMTItNTczNDA1MjQ4Mjk5NDYzMg)**         

        
        ''',
 f'''🔮 **CHEMISTRY 12th ALLEN CLASSROOM LECTURES**

🌱**[CHEMICAL KINETICS ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU4MDYxOTE1MzIyMzAyODAtNTgyNDIyNjI5NDUzOTE5Mg)**

🌱**[CHEMICAL KINETICS DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDIxNzk4MjU5NjkzMjk2LTE0NDM2ODI3MjI4Mjg0MDU2)**

🌱**[CHEMICAL KINETICS VJ SIR  2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0Njk5MzMzMjEzMDAyNjY0LTE0NzExMzU2Mzg3ODc1Mjcy)**

**🌱[CHEMICAL KINETICS VK SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0OTA5NzM4NzczMjczMzA0LTE0OTIzNzY1ODEwNjI0Njgw)**

**🌱[CHEMICAL KINETICS PKP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE1MzU1NTk4MTc0Nzk5MTg0LTE1Mzc4NjQyNTkzMzA1MDE2)**

🌱**[SOLUTION ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU4MjUyMjgyMjU3Nzg1NzYtNTgzNDI0NTYwNjkzMzAzMg)**

🌱**[SOLUTION  DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDM3ODI5MTU5NTIzNDQwLTE0NDU4ODY5NzE1NTUwNTA0)**

🌱**[SOLUTION VJ SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NzE5MzcxODM3NzkwMzQ0LTE0NzI1MzgzNDI1MjI2NjQ4)**

**🌱[SOLUTION VK SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0OTI0NzY3NzQxODY0MDY0LTE0OTM4Nzk0Nzc5MjE1NDQw)** 

🌱**[ELECTROCHEMISTRY  ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU4MzUyNDc1MzgxNzI0MTYtNTg0ODI3MjY0NDI4NDQwOA)**

🌱**[ELECTROCHEMISRTY DP SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0NDU5ODcxNjQ2Nzg5ODg4LTE0NDczODk4Njg0MTQxMjY0)** 

**🌱[ELECTROCHEMISRTY VK SIR 2025](https://t.me/{BOT_USERNM}?start=Z2V0LTE0OTM5Nzk2NzEwNDU0ODI0LTE0OTUyODIxODE2NTY2ODE2)**

🌱**[SOLID STATE ✘ MM SIR ](https://t.me/{BOT_USERNM}?start=Z2V0LTU4NDkyNzQ1NzU1MjM3OTItNTg1NjI4ODA5NDE5OTQ4MA)**
 ''',
          
                
        f'''  🔮 **DN SIR CLASSROOM LECTURES **

🔮**DN SIR**

🌱**[ISOMERISM ](https://t.me/{BOT_USERNM}?start=Z2V0LTQyOTMyNzUzNjA3NjA0NDAtNDMzMDM0NjgxNjYxNzY0OA)** 

🌱**[GOC ](https://t.me/{BOT_USERNM}?start=Z2V0LTQzMzEzNDg3NDc4NTcwMzItNDM0ODM4MTU3ODkyNjU2MA)**

🌱**[REACTION MECHANISM LEC 01 - 32 ](https://t.me/{BOT_USERNM}?start=Z2V0LTQzNDkzODM1MTAxNjU5NDQtNDM4MTQ0NTMwOTgyNjIzMg)**

🌱**[REACTION MECHANISM LEC 33 - 67 ](https://t.me/{BOT_USERNM}?start=Z2V0LTQzNDkzODM1MTAxNjU5NDQtNDM4MTQ0NTMwOTgyNjIzMg)**

🌱**[NITROGEN CONTANING ](https://t.me/{BOT_USERNM}?start=Z2V0LTQ0MTc1MTQ4MzQ0NDQwNTYtNDQxOTUxODY5NjkyMjgyNA)**

🌱**[POLYMER ](https://t.me/{BOT_USERNM}?start=Z2V0LTQ0MjA1MjA2MjgxNjIyMDgtNDQyMTUyMjU1OTQwMTU5Mg)**

🌱**[CHEMISTRY IN EVERYDAY LIFE ](https://t.me/{BOT_USERNM}?start=Z2V0LTQ0MjI1MjQ0OTA2NDA5NzYtNDQyMzUyNjQyMTg4MDM2MA)**

🌱**[NOMENCLATURE ](https://t.me/{BOT_USERNM}?start=Z2V0LTQ0MjQ1MjgzNTMxMTk3NDQtNDQzOTU1NzMyMTcxMDUwNA)**    

''',
          

          
        
    ]
    
    # Send each piece of information as a separate message
    for info in chemualn_info:
        await query.message.reply_text(info, disable_web_page_preview=True ,parse_mode=ParseMode.MARKDOWN)
        
        # Add a short delay between messages (optional)
        await asyncio.sleep(0.1)

        await query.answer("ALLEN CLASSROOM  CHEMISTRY LECTURES SENT SUCESSFULLY✅", show_alert=True)
